- name: Initialize the Cluster
  shell: "kubeadm init --pod-network-cidr={{ pod_ip_range }}"

- name: Create .kube Directory for User
  become: yes
  become_user: "{{ default_username }}"
  file:
    path: "~{{ default_username }}/.kube"
    state: directory
    mode: 0755

- name: Add Kubernetes Config for User
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "~{{ default_username }}/.kube/config"
    remote_src: yes
    owner: "{{ default_username }}"
    group: "{{ default_username }}"

- name: Create Pod Network Config
  template:
    src: files/calico.yaml
    dest: /tmp/calico.yaml

- name: Install Pod Network 
  become: yes
  become_user: "{{ default_username }}"
  shell: kubectl apply -f /tmp/calico.yaml
  args:
    chdir: $HOME

- name: Tidy Up
  file:
    path: /tmp/calico.yaml
    state: absent

- name: Get the Local Join Command
  become: yes
  become_user: "{{ default_username }}"
  shell: kubeadm token create --print-join-command --ttl 0
  register: kubernetes_join_command
  run_once: true

- name: Write Local Join Command
  template:
    src: files/kubernetes_join_command.sh
    dest: "files/{{ cluster_name }}_kubernetes_join_command.sh"
  run_once: true
  delegate_to: localhost

- name: Trust Tunnel Interface Traffic
  firewalld:
    zone: trusted
    interface: tunl0
    state: enabled
    permanent: yes
    immediate: yes
