- name: Obtain Join Command 
  copy:
    src: "files/{{ cluster_name }}_kubernetes_join_command.sh"
    dest: /tmp/kubernetes_join_command.sh
    mode: 0700
  tags:
    - update

- name: Join the Worker Node to the cluster.
  command: bash /tmp/kubernetes_join_command.sh

- name: Tidy Up
  file:
    path: /tmp/kubernetes_join_command.sh
    state: absent

- name: Trust Tunnel Interface Traffic
  firewalld:
    zone: trusted
    source: tunl0
    state: enabled
    permanent: yes
    immediate: yes
